# Generated by Django 2.0.1 on 2018-06-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='shape',
            field=models.IntegerField(choices=[(1, 'Long & thin'), (2, 'Long & thick'), (3, 'Round'), (4, 'Round & flat'), (5, 'Cone')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='texture',
            field=models.IntegerField(choices=[(1, 'Smooth'), (2, 'Soft'), (3, 'Hairy'), (4, 'Hard')], default=1),
            preserve_default=False,
        ),
    ]
